### ISSUE TITLE
Update slf4j-utils:0.6.1 to 0.7.1

### ISSUE THREAD

**Issue by mofadlalla** [Koriit/ktor-logging#2]
Hello, 

I am trying to include this plugin in my project using the jitpack plugin. The issue I'm having is that this project still depends on slf4j-utils:0.6.1 but the earliest version available on github is 0.7.0. Would it be possible to update slf4j-utils dependency to the latest version (0.7.1)?

**Comment by koriit-kontakt** [comment]
Yes absolutely. I guess it's about time I update all of my libraries and migrate them to maven central.

**Comment by Koriit** [comment]
Yes absolutely. I guess it's about time I update all of my libraries and migrate them to maven central.

**Comment by Koriit** [comment]
Hello, this library has been migrated to Maven Central. Additionally, with [0.4.0](https://github.com/Koriit/ktor-logging/releases/tag/0.4.0) I updated all dependencies that could be updated - that includes my `slf4j-utils` which has also been migrated to Maven Central and updated.
